const ERROR_CODE = {
  AUTHERR: 'AUTHORIZATION_ERROR',
  MISSING_AUTH: 'MISSING_AUTHORIZATION',
  INVALID_TOKEN: 'INVALID_AUTH_TOKEN',
  INACTIVE: 'INACTIVE_ACCOUNT',
  EXPIRED: 'EXPIRED_TOKEN',
  PERMISSION: 'PERMISSION_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  LIMIT: 'LIMIT_ERROR',
  FEE: 'FEE_ERROR',
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DUPLICATE: 'DUPLICATE_RECORD',
  APP_ERROR: 'APPLICATION_ERROR',
  RATE_LIMIT: 'RATE_LIMIT_ERROR',
};

const ERROR_STATUS_CODE_MAPPING = {
  AUTHORIZATION_ERROR: 401,
  MISSING_AUTHORIZATION: 401,
  INVALID_AUTH_TOKEN: 401,
  INACTIVE_ACCOUNT: 401,
  EXPIRED_TOKEN: 401,
  PERMISSION_ERROR: 401,
  INVALID_REQUEST: 403,
  LIMIT_ERROR: 403,
  FEE_ERROR: 403,
  RESOURCE_NOT_FOUND: 404,
  DUPLICATE_RECORD: 409,
  APPLICATION_ERROR: 500,
  RATE_LIMIT_ERROR: 429,
  // Custom business rule error codes
  SL02: 400,
  AC01: 400,
  AC05: 400,
  NF01: 404,
  NF02: 404,
  AC03: 403,
  AC04: 403,
};

module.exports = { ERROR_CODE, ERROR_STATUS_CODE_MAPPING };
